language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t prabhus/docker-react-app -f Dockerfile.dev .

script:
    - docker run prabhus/docker-react-app npm run test -- --coverage    